### ISSUE TITLE
Need to specify -g for installation

### ISSUE THREAD

**Issue by TylerMoeller** [azat-co/meanworks#6]
[The Readme](https://github.com/azat-co/meanworks/blob/master/README.md) says to run the following command for the easy installation: 

`$ npm install meanworks@latest`

If we do this and try to run `$ meanworks` or `$ node meanworks.js` after install, we get an error that the command was not found. Verified on Windows 7 and OS X.

People will need to install globally instead: `$ npm install -g meanworks@latest`

Happy to submit a pull request to update the readme if it helps.

**Comment by azat-co** [comment]
@TylerMoeller thank you! fixed in https://github.com/azat-co/meanworks/commit/b53e16675e2973629d8ab5c68bf89c8a569274af
