### ISSUE TITLE
Issues with Problem 3

### ISSUE THREAD

**Issue by TylerMoeller** [azat-co/meanworks#7]
Four issues listed below with respect to Problem 3. Let me know if you want any of these filed separately. Two version number typos, a missing install in the solution provided, and an error preventing me from verifying the solution on Windows:

**1)** Instructions say to Please Install Bower v1.4.1, but when I verify the solution, I'm told the workshop was designed to work with v1.5.3. 

``` bash
You have version 1.4.1, but this workshop was tested to work with 1.5.3 (or later versions)
Run `$ npm install -g bower@1.5.3` to upgrade it
(You can also just skip this if you want- at your own risk!)
```

**2)** Instructions refer to both Yeoman 1.4.7 and 1.5.1. The workshop was designed to work with 1.5.1 according to the warnings when verifying the solution. All references to 1.4.7 should be removed.

**3)** The final solution is missing the instructions for Yeoman:

``` bash

---
SOLUTION

---

$ npm install -g bower@1.5.3
$ npm install -g grunt-cli@0.1.13
$ npm install -g generator-angular-fullstack@3.1.1
$ npm install -g webdriver-manager@8.0.0
```

**4)** Final issue: I get the following error on Windows when attempting to verify the solution:

``` bash
check-version-npm.js:38
        if (args.join('').toLowerCase() === 'skip') {
            ^
ReferenceError: args is not defined
    at check-version-npm.js:38:13
    at ChildProcess.exithandler (child_process.js:204:7)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:818:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```

**Comment by azat-co** [comment]
fixed with a1f9dfe
